name: Claude Code PR Review Example

on:
  issue_comment:
    types: [ created ]
  pull_request_review_comment:
    types: [ created ]
  pull_request_review:
    types: [ submitted ]

jobs:
  claude-review:
    uses: ./.github/workflows/claude-code-review.yml
    with:
      disallowed_tools: |
        Read(README.md)